"use client";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";
import { useState } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [navClose, setNavClose] = useState<boolean>(false);
  return (
    <html lang="en">
      <body className="flex h-screen w-screen gap-1 py-2 pr-2 !bg-[#212023]">
        <Toaster position="top-right" />
        <Navbar setNavClose={setNavClose} navClose={navClose} />
        {children}
      </body>
    </html>
  );
}
