import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" grid grid-cols-6 h-screen w-screen gap-1 p-2 !bg-[#212023]">
        <Toaster position="top-right" />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
